/* Auto-generated by build.py — DO NOT EDIT
 * Bridges dictum_robotics.h Phase 7 type requirements to
 * dictum_niche_stdlib_v1_0 which pre-dates these definitions.
 */
#ifndef DICTUM_ROBOTICS_COMPAT_H
#define DICTUM_ROBOTICS_COMPAT_H

#include "dictum_stdlib.h"   /* niche unified header */

#ifdef __cplusplus
extern "C" {
#endif

/* dictum_bool — C89-safe boolean for struct fields */
#ifndef dictum_bool
  typedef int dictum_bool;
#endif

/* Error sentinel codes */
#ifndef DICTUM_OK
  #define DICTUM_OK             ((dictum_result){.ok = true,  .error = {0}})
#endif
#ifndef DICTUM_ERR_INVALID_ARG
  #define DICTUM_ERR_INVALID_ARG ((dictum_result){.ok = false, .error = "invalid argument"})
#endif
#ifndef DICTUM_ERR_OOM
  #define DICTUM_ERR_OOM         ((dictum_result){.ok = false, .error = "out of memory"})
#endif

/* Convenience: test a dictum_result */
#define DICTUM_IS_OK(r)   ((r).ok)
#define DICTUM_IS_ERR(r)  (!(r).ok)

#ifdef __cplusplus
}
#endif
#endif /* DICTUM_ROBOTICS_COMPAT_H */
