/* Auto-generated by Dictumc Phase 7 — Robotics Shim Implementation */
#include "dictum_robotics.h"
#include <stdlib.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ── Servo ─────────────────────────────────────────── */

typedef struct dictum_servo_ctx {
    dictum_count pin;
    dictum_count freq_hz;
    dictum_whole angle;
} dictum_servo_ctx;

dictum_result dictum_servo_init(dictum_count pin, dictum_count freq_hz, dictum_servo_handle* out) {
    if (!out) return DICTUM_ERR_INVALID_ARG;
    dictum_servo_handle h = (dictum_servo_handle)malloc(sizeof(dictum_servo_ctx));
    if (!h) return DICTUM_ERR_OOM;
    h->pin = pin;
    h->freq_hz = freq_hz;
    h->angle = 0;
    *out = h;
    return DICTUM_OK;
}

dictum_result dictum_servo_set_angle(dictum_servo_handle h, dictum_whole degrees) {
    if (!h) return DICTUM_ERR_INVALID_ARG;
    if (degrees < 0) degrees = 0;
    if (degrees > 180) degrees = 180;
    h->angle = degrees;
    /* Platform-specific PWM output would go here */
    return DICTUM_OK;
}

void dictum_servo_detach(dictum_servo_handle h) {
    if (!h) return;
    /* Platform-specific detach would go here */
    free(h);
}

/* ── DC Motor (H-bridge) ────────────────────────────── */

typedef struct dictum_motor_ctx {
    dictum_count pin_a;
    dictum_count pin_b;
    dictum_count pwm_pin;
    dictum_whole speed;
} dictum_motor_ctx;

dictum_result dictum_motor_init(dictum_count pin_a, dictum_count pin_b, dictum_count pwm_pin, dictum_motor_handle* out) {
    if (!out) return DICTUM_ERR_INVALID_ARG;
    dictum_motor_handle h = (dictum_motor_handle)malloc(sizeof(dictum_motor_ctx));
    if (!h) return DICTUM_ERR_OOM;
    h->pin_a = pin_a;
    h->pin_b = pin_b;
    h->pwm_pin = pwm_pin;
    h->speed = 0;
    *out = h;
    return DICTUM_OK;
}

dictum_result dictum_motor_set_speed(dictum_motor_handle h, dictum_whole speed) {
    if (!h) return DICTUM_ERR_INVALID_ARG;
    if (speed < -1000) speed = -1000;
    if (speed > 1000) speed = 1000;
    h->speed = speed;
    /* Platform-specific H-bridge control would go here */
    return DICTUM_OK;
}

void dictum_motor_stop(dictum_motor_handle h) {
    if (!h) return;
    h->speed = 0;
    /* Platform-specific stop would go here */
}

void dictum_motor_free(dictum_motor_handle h) {
    if (!h) return;
    dictum_motor_stop(h);
    free(h);
}

/* ── Encoder (quadrature) ───────────────────────────── */

typedef struct dictum_encoder_ctx {
    dictum_count pin_a;
    dictum_count pin_b;
    dictum_whole count;
} dictum_encoder_ctx;

dictum_result dictum_encoder_init(dictum_count pin_a, dictum_count pin_b, dictum_encoder_handle* out) {
    if (!out) return DICTUM_ERR_INVALID_ARG;
    dictum_encoder_handle h = (dictum_encoder_handle)malloc(sizeof(dictum_encoder_ctx));
    if (!h) return DICTUM_ERR_OOM;
    h->pin_a = pin_a;
    h->pin_b = pin_b;
    h->count = 0;
    *out = h;
    return DICTUM_OK;
}

dictum_whole dictum_encoder_count(dictum_encoder_handle h) {
    if (!h) return 0;
    return h->count;
}

void dictum_encoder_reset(dictum_encoder_handle h) {
    if (!h) return;
    h->count = 0;
}

void dictum_encoder_free(dictum_encoder_handle h) {
    if (!h) return;
    free(h);
}

/* ── PID Controller ─────────────────────────────────── */

typedef struct dictum_pid_ctx {
    dictum_frac kp;
    dictum_frac ki;
    dictum_frac kd;
    dictum_frac integral;
    dictum_frac prev_error;
    dictum_bool first_run;
} dictum_pid_ctx;

dictum_result dictum_pid_init(dictum_frac kp, dictum_frac ki, dictum_frac kd, dictum_pid_handle* out) {
    if (!out) return DICTUM_ERR_INVALID_ARG;
    dictum_pid_handle h = (dictum_pid_handle)malloc(sizeof(dictum_pid_ctx));
    if (!h) return DICTUM_ERR_OOM;
    h->kp = kp;
    h->ki = ki;
    h->kd = kd;
    h->integral = 0.0;
    h->prev_error = 0.0;
    h->first_run = 1;
    *out = h;
    return DICTUM_OK;
}

dictum_frac dictum_pid_step(dictum_pid_handle h, dictum_frac setpoint, dictum_frac measured, dictum_frac dt) {
    if (!h || dt <= 0.0) return 0.0;
    dictum_frac error = setpoint - measured;
    h->integral += error * dt;
    dictum_frac derivative = 0.0;
    if (!h->first_run) {
        derivative = (error - h->prev_error) / dt;
    } else {
        h->first_run = 0;
    }
    dictum_frac output = h->kp * error + h->ki * h->integral + h->kd * derivative;
    h->prev_error = error;
    return output;
}

void dictum_pid_reset(dictum_pid_handle h) {
    if (!h) return;
    h->integral = 0.0;
    h->prev_error = 0.0;
    h->first_run = 1;
}

void dictum_pid_free(dictum_pid_handle h) {
    if (!h) return;
    free(h);
}

/* ── Kinematics helpers ─────────────────────────────── */

dictum_frac dictum_kin_deg2rad(dictum_frac degrees) {
    return degrees * (M_PI / 180.0);
}

dictum_frac dictum_kin_rad2deg(dictum_frac radians) {
    return radians * (180.0 / M_PI);
}

dictum_frac dictum_kin_map(dictum_frac x, dictum_frac in_min, dictum_frac in_max,
                           dictum_frac out_min, dictum_frac out_max) {
    if (in_max == in_min) return out_min;
    return out_min + (x - in_min) * (out_max - out_min) / (in_max - in_min);
}

dictum_frac dictum_kin_clamp(dictum_frac x, dictum_frac lo, dictum_frac hi) {
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}
