/* Auto-generated by Dictumc Phase 7 — Robotics Shim */
#ifndef DICTUM_ROBOTICS_H
#define DICTUM_ROBOTICS_H
#include "dictum_stdlib.h"
#ifdef __cplusplus
extern "C" {
#endif

/* ── Servo ─────────────────────────────────────────── */
typedef struct dictum_servo_ctx* dictum_servo_handle;
dictum_result dictum_servo_init(dictum_count pin, dictum_count freq_hz, dictum_servo_handle* out);
dictum_result dictum_servo_set_angle(dictum_servo_handle h, dictum_whole degrees);
void          dictum_servo_detach(dictum_servo_handle h);

/* ── DC Motor (H-bridge) ────────────────────────────── */
typedef struct dictum_motor_ctx* dictum_motor_handle;
dictum_result dictum_motor_init(dictum_count pin_a, dictum_count pin_b, dictum_count pwm_pin, dictum_motor_handle* out);
dictum_result dictum_motor_set_speed(dictum_motor_handle h, dictum_whole speed); /* -1000..1000 */
void          dictum_motor_stop(dictum_motor_handle h);
void          dictum_motor_free(dictum_motor_handle h);

/* ── Encoder (quadrature) ───────────────────────────── */
typedef struct dictum_encoder_ctx* dictum_encoder_handle;
dictum_result dictum_encoder_init(dictum_count pin_a, dictum_count pin_b, dictum_encoder_handle* out);
dictum_whole  dictum_encoder_count(dictum_encoder_handle h);
void          dictum_encoder_reset(dictum_encoder_handle h);
void          dictum_encoder_free(dictum_encoder_handle h);

/* ── PID Controller ─────────────────────────────────── */
typedef struct dictum_pid_ctx* dictum_pid_handle;
dictum_result dictum_pid_init(dictum_frac kp, dictum_frac ki, dictum_frac kd, dictum_pid_handle* out);
dictum_frac   dictum_pid_step(dictum_pid_handle h, dictum_frac setpoint, dictum_frac measured, dictum_frac dt);
void          dictum_pid_reset(dictum_pid_handle h);
void          dictum_pid_free(dictum_pid_handle h);

/* ── Kinematics helpers ─────────────────────────────── */
dictum_frac   dictum_kin_deg2rad(dictum_frac degrees);
dictum_frac   dictum_kin_rad2deg(dictum_frac radians);
dictum_frac   dictum_kin_map(dictum_frac x, dictum_frac in_min, dictum_frac in_max,
                             dictum_frac out_min, dictum_frac out_max);
dictum_frac   dictum_kin_clamp(dictum_frac x, dictum_frac lo, dictum_frac hi);

#ifdef __cplusplus
}
#endif
#endif /* DICTUM_ROBOTICS_H */

